apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: REPO
    description: Application name
    value: nr-sustainment-capstone-2025
  - name: TAG
    description: Image tag; e.g. PR number or latest
    required: true
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: TARGET
    description: Deployment target; e.g. PR number, test or prod
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 5173
          protocol: TCP
          name: http-5173
      selector:
        service: ${REPO}-${TARGET}-${COMPONENT}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
        deployment: ${REPO}-${TARGET}-${COMPONENT}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: ${REPO}-${TARGET}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${REPO}-${TARGET}
            deployment: ${REPO}-${TARGET}-${COMPONENT}
            service: ${REPO}-${TARGET}-${COMPONENT}
        spec:
          containers:
            - name: ${REPO}-${TARGET}-${COMPONENT}
              image: ghcr.io/bcgov/${REPO}/${COMPONENT}:${TAG}
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              # securityContext:
              #   runAsUser: 1011540000
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VITE_BACKEND_URL
                  value: https://nr-sustainment-capstone-2025-145-backend.apps.silver.devops.gov.bc.ca
              ports:
                - name: http
                  containerPort: 5173
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 3
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 150m
                  memory: 250Mi
                requests:
                  cpu: 50m
                  memory: 175Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      host: soil-assessment-tool-${TARGET}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: http-5173
      to:
        kind: Service
        name: ${REPO}-${TARGET}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
