# Reusable vars
x-var:
  - &POSTGRES_USER
    postgres

# Postgres envars
x-postgres-vars: &postgres-vars
  POSTGRES_DATABASE: postgres
  POSTGRES_HOST: sat-db
  POSTGRES_PASSWORD: default
  POSTGRES_USER: *POSTGRES_USER

name: Soil-Assessment-Tool
services:
  # DB
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    # Don't put an image: prop here, it breaks the local
    container_name: sat-db
    environment:
      <<: *postgres-vars
    ports: [5432:5432]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PGAdmin
  pgadmin:
    container_name: sat-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports: [5050:80]
    profiles: ["pgadmin"]

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sat-api
    depends_on:
      database:
        condition: service_healthy
    develop:
     watch:
       - action: sync
         path: ./backend/
         target: /app
         ignore: [node_modules]
    environment:
      LOG_LEVEL: info
      PORT: 3000
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports: ["3000:3000"]
    volumes: ["./backend:/app", "/app/node_modules"]
    # For debugging
    stdin_open: true
    tty: true

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sat-frontend
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: [node_modules]
    environment:
      VITE_BACKEND_URL: http://localhost:3000/api
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
    ports: ["5173:5173"]
    volumes: ["./frontend:/app", "/app/node_modules"]

volumes:
  postgres_data:
