apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: REPO
    description: Repository Name
    value: nr-sustainment-capstone-2025
  - name: TAG
    required: true
  - name: COMPONENT
    description: Component name
    value: database
  - name: TARGET
    description: Deployment target, e.g. pr-###, test or prod
    required: true
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${REPO}-${TARGET}-${COMPONENT}
      labels:
        app: ${REPO}-${TARGET}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 128Mi
      storageClassName: netapp-file-standard
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${REPO}-${TARGET}-${COMPONENT}
      labels:
        app: ${REPO}-${TARGET}
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: ${REPO}-${TARGET}-${COMPONENT}
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        activeDeadlineSeconds: 21600
      template:
        metadata:
          name: ${REPO}-${TARGET}-${COMPONENT}
          labels:
            app: ${REPO}-${TARGET}
            deployment: ${REPO}-${TARGET}-${COMPONENT}
        spec:
          volumes:
            - name: ${REPO}-${TARGET}-${COMPONENT}
              persistentVolumeClaim:
                claimName: ${REPO}-${TARGET}-${COMPONENT}
          containers:
            - name: ${REPO}-${TARGET}
              image: ghcr.io/bcgov/${REPO}/${COMPONENT}:${TAG}
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources:
                requests:
                  cpu: 50m
                  memory: 150Mi
                limits:
                  cpu: 115m
                  memory: 250Mi
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - "-c"
                    - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                successThreshold: 1
                failureThreshold: 5
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 10
              livenessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - "-c"
                    - psql -q $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                successThreshold: 1
                failureThreshold: 5
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 10
              env:
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-${TARGET}-${COMPONENT}
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-${TARGET}-${COMPONENT}
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-${TARGET}-${COMPONENT}
                      key: database-user
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-${TARGET}-${COMPONENT}
                      key: database-host
              volumeMounts:
                - name: ${REPO}-${TARGET}-${COMPONENT}
                  mountPath: "/var/lib/postgresql"
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        deployment: ${REPO}-${TARGET}-${COMPONENT}
      sessionAffinity: None
      type: ClusterIP
